import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { Fragment } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Link href={'/'} passHref> 
            Home
          </Link>
          <Link href={'/events'} passHref> 
            Events
          </Link>
          <Link href={'/about-us'} passHref> 
            About Us
          </Link>
          
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev) => (
        <Link key={ev.id} href={`/events/${ev.id}`} passHref>
          <Fragment>
            <Image width={300} height={300} alt={ev.title} src={ev.image}/>
            <h2> {ev.title} </h2>
            <p> {ev.description} </p> 
          </Fragment>
        </Link>
        ))}

      </main>
      <footer className={styles.footer}>
        <p> 2023 - A Next.js Project</p>
      </footer>
    </>
  )
}


export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');
  
  return {
      props:{
          data: events_categories,
      }
  }
}